dist: bionic
language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.pio"

install:
    - pip install -U platformio

script:
    - g++ -v
    - pio run -e universal
    - make test
